version: '3.8'

volumes:
  data:

services:
  postgres-dis:
    image: postgres:14.8
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dis_db
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql
