spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/disagreed_db?currentSchema=independent_repo
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
    contexts: dev