{
 "title": "Custom",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Запросы с помощью mybatis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Запрос с 13 join",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "method_timed_seconds_sum{class=\"com.disagreed.independentrepo.repository.impl.mybatis.MybatisIndependentRestaurantRepositoryImpl\", method=\"getAll\"} / method_timed_seconds_count{class=\"com.disagreed.independentrepo.repository.impl.mybatis.MybatisIndependentRestaurantRepositoryImpl\", method=\"getAll\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Запрос с 6 join",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "method_timed_seconds_sum{class=\"com.disagreed.independentrepo.repository.impl.mybatis.MybatisIndependentDishRepositoryImpl\", method=\"getAll\"} / method_timed_seconds_count{class=\"com.disagreed.independentrepo.repository.impl.mybatis.MybatisIndependentDishRepositoryImpl\", method=\"getAll\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Запрос без join",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "method_timed_seconds_sum{class=\"com.disagreed.independentrepo.repository.impl.mybatis.MybatisIndependentCountryRepositoryImpl\", method=\"getAll\"} / method_timed_seconds_count{class=\"com.disagreed.independentrepo.repository.impl.mybatis.MybatisIndependentCountryRepositoryImpl\", method=\"getAll\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "Запросы с помощью hibernate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Запрос с 13 join",
   "type": "timeseries",
   "description": "График отображает среднее время запроса",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "method_timed_seconds_sum{class=\"com.disagreed.independentrepo.repository.impl.hibernate.HibernateIndependentRestaurantRepositoryImpl\", method=\"getAll\"} / method_timed_seconds_count{class=\"com.disagreed.independentrepo.repository.impl.hibernate.HibernateIndependentRestaurantRepositoryImpl\", method=\"getAll\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Запрос с 6 join",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "method_timed_seconds_sum{class=\"com.disagreed.independentrepo.repository.impl.hibernate.HibernateIndependentDishRepositoryImpl\", method=\"getAll\"} / method_timed_seconds_count{class=\"com.disagreed.independentrepo.repository.impl.hibernate.HibernateIndependentDishRepositoryImpl\", method=\"getAll\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Запрос без join",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "method_timed_seconds_sum{class=\"com.disagreed.independentrepo.repository.impl.hibernate.HibernateIndependentCountryRepositoryImpl\",method=\"getAll\"} / method_timed_seconds_count{class=\"com.disagreed.independentrepo.repository.impl.hibernate.HibernateIndependentCountryRepositoryImpl\", method=\"getAll\"}",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}