version: '3.8'
name: independent-repo
volumes:
  data:

networks:
  kafka-net:
    name: kafka-net
    driver: bridge

services:
  postgres-dis:
    image: postgres:14.8
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dis_db
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql

  grafana:
    build: 'config/grafana'
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"