server:
  port: 9000
  servlet:
    context-path: /demo
    session:
      timeout: 14400

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dis_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
    contexts: dev
    default-schema: public

  docker:
    compose:
      enabled: true
      stop:
        command: stop

## hibernate or mybatis
repository:
  name: mybatis

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml

logging:
  level:
    com.disagreed.independentrepo: DEBUG
